#!/bin/bash
############################################################
# stopvpn
# This script is used to stop a running Docker container.
############################################################


source ./.defaults
source ./settings

echo "Shutting down $VPN_NAME."

docker-compose -f $VPN_NAME/composer/docker-compose.yml \
    --env-file $VPN_NAME/composer/envvars \
    down --rmi all